# Generated by Django 5.2.4 on 2025-07-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', '남성'), ('FEMALE', '여성')], max_length=10, null=True, verbose_name='성별'),
        ),
    ]
