# Generated by Django 5.2.4 on 2025-07-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0003_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='크롤링 대상 이름')),
                ('url', models.URLField(max_length=500, verbose_name='크롤링 대상 URL')),
                ('xpath', models.CharField(max_length=500, verbose_name='크롤링 대상 XPath')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'crawl_target',
            },
        ),
    ]
