# Generated by Django 5.2.4 on 2025-07-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0004_crawltarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='금 가격')),
                ('naver_price', models.IntegerField(verbose_name='네이버 금 가격')),
                ('updated_at', models.DateTimeField(verbose_name='수정일')),
                ('naver_updated_at', models.DateTimeField(verbose_name='네이버 수정일')),
            ],
            options={
                'db_table': 'gold_price',
            },
        ),
    ]
