# Generated by Django 5.2.4 on 2025-07-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0005_goldprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldprice',
            name='naver_price',
            field=models.PositiveIntegerField(verbose_name='네이버 금 가격'),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='price',
            field=models.PositiveIntegerField(verbose_name='금 가격'),
        ),
    ]
