# Generated by Django 5.2.4 on 2025-07-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0006_alter_goldprice_naver_price_alter_goldprice_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='금 가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'db_table': 'gold_price_history',
            },
        ),
    ]
