# Generated by Django 5.2.4 on 2025-07-06 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0007_goldpricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_product_no', models.BigIntegerField(unique=True, verbose_name='원 상품 번호')),
                ('channel_product_no', models.BigIntegerField(unique=True, verbose_name='채널 상품 번호')),
                ('name', models.CharField(max_length=255, verbose_name='상품명')),
                ('gold', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='돈수')),
                ('labor_cost', models.PositiveIntegerField(verbose_name='공임비')),
                ('sub_cost', models.PositiveIntegerField(verbose_name='부가비용')),
                ('markup_rate', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='판매가 배율')),
                ('price', models.PositiveIntegerField(verbose_name='판매가')),
                ('option_group_quantity', models.PositiveIntegerField(default=0, verbose_name='옵션 그룹 수량')),
                ('option_group_name1', models.CharField(max_length=255, null=True, verbose_name='옵션 그룹명1')),
                ('option_group_name2', models.CharField(max_length=255, null=True, verbose_name='옵션 그룹명2')),
                ('option_group_name3', models.CharField(max_length=255, null=True, verbose_name='옵션 그룹명3')),
                ('option_group_flag', models.BooleanField(default=False, verbose_name='옵션 그룹 업데이트 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='GroupOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.BigIntegerField(unique=True, verbose_name='옵션 ID')),
                ('option_name1', models.CharField(max_length=255, null=True, verbose_name='옵션명1')),
                ('option_name2', models.CharField(max_length=255, null=True, verbose_name='옵션명2')),
                ('option_name3', models.CharField(max_length=255, null=True, verbose_name='옵션명3')),
                ('gold', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='돈수')),
                ('sub_cost', models.PositiveIntegerField(verbose_name='부가비용')),
                ('markup_rate', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='판매가 배율')),
                ('price', models.PositiveIntegerField(verbose_name='판매가')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='system_manage.product')),
            ],
            options={
                'db_table': 'group_option',
            },
        ),
    ]
