# Generated by Django 5.2.4 on 2025-07-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0008_product_groupoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupoption',
            name='gold',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='중량'),
        ),
        migrations.AlterField(
            model_name='groupoption',
            name='price',
            field=models.IntegerField(verbose_name='판매가'),
        ),
        migrations.AlterField(
            model_name='groupoption',
            name='sub_cost',
            field=models.IntegerField(verbose_name='부가비용'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gold',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='중량'),
        ),
    ]
