# Generated by Django 5.2.4 on 2025-07-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0009_alter_groupoption_gold_alter_groupoption_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth',
            field=models.DateField(default='2000-01-01', null=True, verbose_name='생년월일'),
        ),
    ]
