# Generated by Django 5.2.4 on 2025-07-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0011_applytaskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='applytaskhistory',
            name='status_message',
            field=models.CharField(default='작업 준비 중...', max_length=255),
        ),
    ]
