# Generated by Django 5.2.4 on 2025-07-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0014_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
