# Generated by Django 5.2.4 on 2026-01-08 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0015_loginhistory_is_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='회원명')),
                ('phone', models.CharField(max_length=20, null=True, unique=True, verbose_name='전화번호')),
                ('gender', models.CharField(choices=[('MALE', '남성'), ('FEMALE', '여성')], max_length=10, null=True, verbose_name='성별')),
                ('comment', models.TextField(null=True, verbose_name='비고')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=100, verbose_name='주문명')),
                ('order_date', models.DateField(verbose_name='주문일')),
                ('total_price', models.PositiveIntegerField(verbose_name='총 가격')),
                ('status', models.CharField(max_length=10, verbose_name='주문 상태')),
                ('comment', models.TextField(null=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='system_manage.customer')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
