# Generated by Django 5.2.4 on 2026-01-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0016_customer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birth',
            field=models.DateField(default='2000-01-01', verbose_name='생년월일'),
        ),
    ]
