# Generated by Django 5.2.4 on 2026-01-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0018_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', '주문요청'), ('1', '제작완료'), ('2', '수령완료'), ('3', '취소')], default='0', max_length=10, verbose_name='주문상태'),
        ),
    ]
