# Generated by Django 5.2.4 on 2026-01-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0019_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth',
            field=models.DateField(null=True, verbose_name='생년월일'),
        ),
    ]
