# Generated by Django 5.2.4 on 2026-01-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0020_alter_customer_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='option',
            field=models.CharField(choices=[('0', 'x'), ('1', '환산'), ('2', '별도')], default='0', max_length=10, verbose_name='옵션상태'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_note',
            field=models.CharField(default='', max_length=100, verbose_name='중요'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', '주문요청'), ('1', '주문완료'), ('2', '전달완료'), ('3', '주문취소')], default='0', max_length=10, verbose_name='주문상태'),
        ),
    ]
