# Generated by Django 5.2.4 on 2026-01-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0021_remove_order_total_price_order_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='comment',
            field=models.TextField(default='', verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='order',
            name='option',
            field=models.CharField(choices=[('0', '없음'), ('1', '환산'), ('2', '별도')], default='0', max_length=10, verbose_name='옵션상태'),
        ),
    ]
