# Generated by Django 5.2.4 on 2026-01-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0022_alter_customer_comment_alter_order_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
