# Generated by Django 5.2.4 on 2026-01-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0023_order_buyer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='engraving_text',
            field=models.CharField(default='', max_length=20, verbose_name='각인 문구'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', '주문요청'), ('1', '주문완료'), ('2', '전달완료'), ('3', '주문취소')], db_index=True, default='0', max_length=10, verbose_name='주문상태'),
        ),
    ]
